### ISSUE TITLE
Open desktop session by name from command line?

### ISSUE THREAD

**Issue by patrickkidd** [ffevotte/desktop-plus#1]
Hello! Excellent package you've done. Is there a way to load a desktop session by name form the command line? Something like:

emacs --eval "(desktop-load my-session-name)"

I am no lisp expert.

Thanks!

**Comment by tripleee** [comment]
http://stackoverflow.com/questions/28733086/load-emacs-desktop-plus-session-from-command-line

**Comment by ffevotte** [comment]
Something like this should work:

    emacs --eval '(desktop-load "my-session-name")'

**Comment by tripleee** [comment]
However, you need double quotes around the `eval` if you want to use it in a shell function which takes a desktop session file name as its argument.  Repeating here the StackOverflow suggested solution:

    emd () {
       cd $HOME/Sites/"$1" &&
       emacs --eval "(progn (require 'desktop+) (desktop-load \"$1-desktop-name\"))" &
    }

**Comment by ffevotte** [comment]
Yes, this is the correct way to wrap it inside a shell function.
Like I said in the StackOverflow thread, `require`ing the package isn't necessary (as `desktop-load` is autoloaded), but it doesn't hurt either.

**Comment by patrickkidd** [comment]
This has all worked well for me. I'm looking forward to the day when I am in one emacs session 100%, but this will be great in the meantime.

Thanks again for the great package.
