### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by gavv** [ffevotte/desktop-plus#11]
Hi,

I would like to package desktop-plus for Gentoo.

Could you please tag a new release? The latest one seems to be quite outdated.

**Comment by ffevotte** [comment]
Hi,

thanks for your comment. I just tagged v0.2, and updated the `stable` branch.

I'm closing the bug, but please feel free to re-open it if there is something more that you need.

**Comment by gavv** [comment]
Thanks! `desktop+` is finally [packaged](https://packages.gentoo.org/packages/app-emacs/desktop+).
