### ISSUE TITLE
Save indirect buffers

### ISSUE THREAD

**Issue by jaksz** [ffevotte/desktop-plus#2]
Would it be also possible to save indirect buffers? I use those a lot with large org files, often having several indirect buffers open, but currently this extension only saves the main buffer.

**Comment by ffevotte** [comment]
That's a very good idea, thank you very much. I also tend to use indirect buffer clones, but never thought about saving them in the session.

I'll try to see what I can do. If you don't hear from me about this in a week, would you please poke me again here?

**Comment by ffevotte** [comment]
By the way, which version are you using? Did you install the `dev` branch, which introduces the machinery to save & restore special buffers?

**Comment by ffevotte** [comment]
The new version in the `dev`branch should add the feature you want. Be sure to update your `init.el` file though: the API to activate special buffers handling changed a bit. The README explains the new way of doing things, but in two words, you should replace all your 

    (add-to-list 'desktop+/special-buffer-modes ...)

by a single call:

    (desktop+/special-buffer-handlers)

which activates special buffer handling for all supported buffer types (including indirect buffers).

Please test and let me know if you have any difficulty.

**Comment by jaksz** [comment]
Thanks for the quick fix; I am currently not using desktop+ anymore so I cannot check it, hopefully somebody else will!
