### ISSUE TITLE
"Wrote /home/robin/.emacs-buffers" message keeps appearing in minibuffer

### ISSUE THREAD

**Issue by greenrd** [ffevotte/desktop-plus#5]
This behaviour is kind of annoying. Can it be disabled?

**Comment by ffevotte** [comment]
Thanks for the report.

This should now be fixed: now `desktop+` keeps quiet when writing the `.emacs-buffers` file to disk.

Please feel free to re-open the issue if something goes wrong (or open a new one if you have other problems).
